[build-system]
requires = [
    "setuptools>=80.0",
    "setuptools-scm[simple]>=9.2"
]
build-backend = "setuptools.build_meta"


[project]
name = "car-utils"
authors = [
  { name = "Eric Torstenson", email = "eric.s.torstenson@vumc.org" },
]
description = "Common Python utilities for Carroll lab tools (logging setup, LinkML model loading)."
readme = "README.md"
requires-python = ">=3.10"

dynamic = ["version"]

classifiers = [
    "Programming Language :: Python :: 3",
]

dependencies = [
  "sqlalchemy",
  "requests",
  "py-horned-owl>=2.0.0",
]

[project.optional-dependencies]
dev = [
    "rich",
    "pytest",
]

[tool.setuptools.packages.find]
where = ["src"]
